# This file defines automatic production of release notes. 

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🍾 Features
      labels:
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug-fix
    - title: 📗 Documentation
      labels:
        - doc
    - title: 📍 Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
