# This a sample actions compatible with devenv

name: "Main Workflow"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build Pipeline
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v23
    - uses: cachix/cachix-action@v12
      with:
        name: devenv

    - name: Install devenv.sh
      run: nix profile install tarball+https://install.devenv.sh/latest

    - name: Prepare the devenv shell
      run: devenv ci

    - name: (devenv) Setup the dependencies
      run: devenv shell setup

    - name: (devenv) Initialize the project
      run: devenv shell init

    - name: (devenv) Run the tests
      run: devenv shell test

    - name: (devenv) Build the project
      run: devenv shell build
  
    

